version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jelly-tech-db
    restart: always
    environment:
      POSTGRES_USER: jelly
      POSTGRES_PASSWORD: jellypass
      POSTGRES_DB: jellytech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
